<?php
$courses = array(
    array(
        'id' => 1,
        'title' => 'Introduction to Web Development',
        'category' => 'tech',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.5,
        'enrolled' => 1234,
        'description' => 'Learn the fundamentals of web development including HTML, CSS, and JavaScript.',
        'skills' => array('HTML', 'CSS', 'JavaScript')
    ),
    array(
        'id' => 2,
        'title' => 'Business Communication',
        'category' => 'business',
        'duration' => '4 weeks',
        'level' => 'Intermediate',
        'rating' => 4.8,
        'enrolled' => 2156,
        'description' => 'Master the art of professional communication in the workplace.',
        'skills' => array('Communication', 'Presentation', 'Writing')
    ),
    array(
        'id' => 3,
        'title' => 'UI/UX Design Fundamentals',
        'category' => 'design',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 1789,
        'description' => 'Learn the principles of user interface and experience design.',
        'skills' => array('Figma', 'Design Thinking', 'Prototyping')
    ),
    array(
        'id' => 4,
        'title' => 'Python for Data Science',
        'category' => 'tech',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 3421,
        'description' => 'Master Python programming for data analysis and visualization.',
        'skills' => array('Python', 'Pandas', 'NumPy', 'Matplotlib')
    ),
    array(
        'id' => 5,
        'title' => 'Digital Marketing Essentials',
        'category' => 'business',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.4,
        'enrolled' => 2890,
        'description' => 'Learn core concepts of digital marketing and social media strategy.',
        'skills' => array('Social Media', 'SEO', 'Content Marketing')
    ),
    array(
        'id' => 6,
        'title' => 'Project Management Fundamentals',
        'category' => 'business',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.9,
        'enrolled' => 1567,
        'description' => 'Learn essential project management methodologies and tools.',
        'skills' => array('Agile', 'Scrum', 'Project Planning')
    ),
    array(
        'id' => 7,
        'title' => 'React.js Development',
        'category' => 'tech',
        'duration' => '12 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 2345,
        'description' => 'Build modern web applications using React.js and its ecosystem.',
        'skills' => array('React', 'Redux', 'JavaScript', 'REST APIs')
    ),
    array(
        'id' => 8,
        'title' => 'Leadership & Team Management',
        'category' => 'soft skills',
        'duration' => '5 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1890,
        'description' => 'Develop essential leadership skills for managing teams effectively.',
        'skills' => array('Leadership', 'Conflict Resolution', 'Team Building')
    ),
    array(
        'id' => 9,
        'title' => 'Data Analytics with SQL',
        'category' => 'tech',
        'duration' => '7 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 2678,
        'description' => 'Master SQL for data analysis and database management.',
        'skills' => array('SQL', 'Database Design', 'Data Analysis')
    ),
    array(
        'id' => 10,
        'title' => 'Brand Strategy & Marketing',
        'category' => 'business',
        'duration' => '6 weeks',
        'level' => 'Intermediate',
        'rating' => 4.5,
        'enrolled' => 1456,
        'description' => 'Learn to build and maintain strong brand presence in the market.',
        'skills' => array('Brand Management', 'Marketing Strategy', 'Consumer Behavior')
    ),
    array(
        'id' => 11,
        'title' => 'Mobile App Design',
        'category' => 'design',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1234,
        'description' => 'Create engaging mobile app interfaces and experiences.',
        'skills' => array('Mobile UI', 'Interaction Design', 'Wireframing')
    ),
    array(
        'id' => 12,
        'title' => 'Public Speaking Mastery',
        'category' => 'soft skills',
        'duration' => '4 weeks',
        'level' => 'Beginner',
        'rating' => 4.8,
        'enrolled' => 3456,
        'description' => 'Build confidence and master the art of public speaking.',
        'skills' => array('Public Speaking', 'Storytelling', 'Audience Engagement')
    ),
    array(
        'id' => 13,
        'title' => 'Machine Learning Basics',
        'category' => 'tech',
        'duration' => '12 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 1789,
        'description' => 'Introduction to machine learning algorithms and applications.',
        'skills' => array('Python', 'Scikit-learn', 'TensorFlow')
    ),
    array(
        'id' => 14,
        'title' => 'Financial Management',
        'category' => 'business',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 2134,
        'description' => 'Understand key concepts of financial management and analysis.',
        'skills' => array('Financial Analysis', 'Budgeting', 'Risk Management')
    ),
    array(
        'id' => 15,
        'title' => 'Cloud Computing Fundamentals',
        'category' => 'tech',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1567,
        'description' => 'Learn basic concepts of cloud computing and major platforms.',
        'skills' => array('AWS', 'Azure', 'Cloud Architecture')
    ),
    array(
        'id' => 16,
        'title' => 'Cybersecurity Essentials',
        'category' => 'tech',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.8,
        'enrolled' => 2345,
        'description' => 'Learn fundamental concepts of cybersecurity and network protection.',
        'skills' => array('Network Security', 'Cryptography', 'Security Protocols')
    ),
    array(
        'id' => 17,
        'title' => 'Content Creation & Strategy',
        'category' => 'business',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 1890,
        'description' => 'Master the art of creating engaging content across different platforms.',
        'skills' => array('Content Writing', 'Video Production', 'Social Media Strategy')
    ),
    array(
        'id' => 18,
        'title' => 'Advanced Data Visualization',
        'category' => 'tech',
        'duration' => '8 weeks',
        'level' => 'Advanced',
        'rating' => 4.7,
        'enrolled' => 1456,
        'description' => 'Create compelling data stories using advanced visualization techniques.',
        'skills' => array('Tableau', 'D3.js', 'Data Storytelling')
    ),
    array(
        'id' => 19,
        'title' => 'Agile Product Management',
        'category' => 'business',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.9,
        'enrolled' => 2156,
        'description' => 'Learn to manage product development using agile methodologies.',
        'skills' => array('Product Strategy', 'Scrum', 'User Stories')
    ),
    array(
        'id' => 20,
        'title' => 'Motion Graphics Design',
        'category' => 'design',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.8,
        'enrolled' => 1678,
        'description' => 'Create engaging motion graphics for digital platforms.',
        'skills' => array('After Effects', 'Animation', 'Visual Storytelling')
    ),
    array(
        'id' => 21,
        'title' => 'Emotional Intelligence at Work',
        'category' => 'soft skills',
        'duration' => '4 weeks',
        'level' => 'Beginner',
        'rating' => 4.7,
        'enrolled' => 2890,
        'description' => 'Develop emotional intelligence skills for better workplace relationships.',
        'skills' => array('Self-awareness', 'Empathy', 'Relationship Management')
    ),
    array(
        'id' => 22,
        'title' => 'DevOps Engineering',
        'category' => 'tech',
        'duration' => '12 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 1567,
        'description' => 'Master modern DevOps practices and tools.',
        'skills' => array('Docker', 'Jenkins', 'Kubernetes')
    ),
    array(
        'id' => 23,
        'title' => 'Advanced Excel for Business',
        'category' => 'business',
        'duration' => '6 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 3421,
        'description' => 'Master advanced Excel functions for business analysis.',
        'skills' => array('Excel', 'Pivot Tables', 'Macros')
    ),
    array(
        'id' => 24,
        'title' => 'Natural Language Processing',
        'category' => 'tech',
        'duration' => '10 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 1234,
        'description' => 'Learn to process and analyze text data using AI techniques.',
        'skills' => array('Python', 'NLTK', 'SpaCy')
    ),
    array(
        'id' => 25,
        'title' => '3D Design Fundamentals',
        'category' => 'design',
        'duration' => '12 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1890,
        'description' => 'Learn the basics of 3D modeling and rendering.',
        'skills' => array('Blender', '3D Modeling', 'Texturing')
    ),
    array(
        'id' => 26,
        'title' => 'Email Marketing Mastery',
        'category' => 'business',
        'duration' => '5 weeks',
        'level' => 'Intermediate',
        'rating' => 4.5,
        'enrolled' => 2156,
        'description' => 'Create effective email marketing campaigns and strategies.',
        'skills' => array('Email Design', 'Campaign Management', 'Analytics')
    ),
    array(
        'id' => 27,
        'title' => 'Critical Thinking and Problem Solving',
        'category' => 'soft skills',
        'duration' => '6 weeks',
        'level' => 'Intermediate',
        'rating' => 4.8,
        'enrolled' => 1789,
        'description' => 'Develop advanced problem-solving and analytical thinking skills.',
        'skills' => array('Analysis', 'Decision Making', 'Logic')
    ),
    array(
        'id' => 28,
        'title' => 'Blockchain Development',
        'category' => 'tech',
        'duration' => '12 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 1456,
        'description' => 'Learn to build applications using blockchain technology.',
        'skills' => array('Solidity', 'Smart Contracts', 'Web3.js')
    ),
    array(
        'id' => 29,
        'title' => 'Business Analytics',
        'category' => 'business',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 2678,
        'description' => 'Learn to use data analytics for business decision making.',
        'skills' => array('Data Analysis', 'Business Intelligence', 'Reporting')
    ),
    array(
        'id' => 30,
        'title' => 'Game Design Principles',
        'category' => 'design',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 1567,
        'description' => 'Master the fundamentals of game design and development.',
        'skills' => array('Game Mechanics', 'Level Design', 'Unity')
    ),
    array(
        'id' => 31,
        'title' => 'Introduction to Healthcare Management',
        'category' => 'healthcare',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.8,
        'enrolled' => 1890,
        'description' => 'Learn the basics of managing healthcare facilities and services.',
        'skills' => array('Healthcare Administration', 'Patient Care', 'Health Policy')
    ),
    array(
        'id' => 32,
        'title' => 'Public Health and Epidemiology',
        'category' => 'healthcare',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.9,
        'enrolled' => 2100,
        'description' => 'Understand the principles of public health and the study of disease patterns.',
        'skills' => array('Epidemiology', 'Public Health Policy', 'Disease Prevention')
    ),
    array(
        'id' => 33,
        'title' => 'Digital Media Strategies',
        'category' => 'media & communications',
        'duration' => '7 weeks',
        'level' => 'Intermediate',
        'rating' => 4.5,
        'enrolled' => 1750,
        'description' => 'Explore strategies for effective digital media campaigns.',
        'skills' => array('Digital Marketing', 'Content Creation', 'Social Media Management')
    ),
    array(
        'id' => 34,
        'title' => 'Journalism in the Digital Age',
        'category' => 'media & communications',
        'duration' => '9 weeks',
        'level' => 'Advanced',
        'rating' => 4.7,
        'enrolled' => 1420,
        'description' => 'Learn the skills needed for modern journalism in a digital world.',
        'skills' => array('Investigative Reporting', 'Digital Journalism', 'Media Ethics')
    ),
    array(
        'id' => 35,
        'title' => 'Introduction to Criminal Law',
        'category' => 'law',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 1600,
        'description' => 'Understand the fundamentals of criminal law and the justice system.',
        'skills' => array('Criminal Law', 'Legal Procedures', 'Case Analysis')
    ),
    array(
        'id' => 36,
        'title' => 'Corporate Law and Governance',
        'category' => 'law',
        'duration' => '10 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 1300,
        'description' => 'Learn about corporate law and the principles of corporate governance.',
        'skills' => array('Corporate Law', 'Governance', 'Regulatory Compliance')
    ),
    array(
        'id' => 37,
        'title' => 'Introduction to Sociology',
        'category' => 'social science',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.5,
        'enrolled' => 2200,
        'description' => 'Explore the study of society, social institutions, and social relationships.',
        'skills' => array('Sociological Theory', 'Social Research', 'Cultural Studies')
    ),
    array(
        'id' => 38,
        'title' => 'Psychology of Human Behavior',
        'category' => 'social science',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1950,
        'description' => 'Understand the psychological principles behind human behavior.',
        'skills' => array('Behavioral Psychology', 'Cognitive Psychology', 'Research Methods')
    ),
    array(
        'id' => 39,
        'title' => 'Financial Accounting Fundamentals',
        'category' => 'accountancy',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 2500,
        'description' => 'Learn the basics of financial accounting and reporting.',
        'skills' => array('Financial Reporting', 'Accounting Principles', 'Bookkeeping')
    ),
    array(
        'id' => 40,
        'title' => 'Advanced Managerial Accounting',
        'category' => 'accountancy',
        'duration' => '10 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 1800,
        'description' => 'Master advanced concepts in managerial accounting and decision-making.',
        'skills' => array('Cost Management', 'Budgeting', 'Financial Analysis')
    ),
    array(
        'id' => 41,
        'title' => 'Teaching Strategies for the 21st Century',
        'category' => 'education',
        'duration' => '7 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 2100,
        'description' => 'Explore modern teaching strategies and techniques.',
        'skills' => array('Instructional Design', 'Classroom Management', 'Educational Technology')
    ),
    array(
        'id' => 42,
        'title' => 'Curriculum Development and Assessment',
        'category' => 'education',
        'duration' => '9 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 1700,
        'description' => 'Learn how to develop and assess effective curricula.',
        'skills' => array('Curriculum Design', 'Assessment Methods', 'Educational Research')
    ),
    array(
        'id' => 43,
        'title' => 'Healthcare Data Analytics',
        'category' => 'healthcare',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.8,
        'enrolled' => 2200,
        'description' => 'Analyze healthcare data to improve patient outcomes and operational efficiency.',
        'skills' => array('Data Analysis', 'Healthcare Informatics', 'Statistical Methods')
    ),
    array(
        'id' => 44,
        'title' => 'Nutrition and Dietetics',
        'category' => 'healthcare',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.7,
        'enrolled' => 1800,
        'description' => 'Learn the principles of nutrition and diet planning for various populations.',
        'skills' => array('Nutritional Science', 'Diet Planning', 'Public Health Nutrition')
    ),
    array(
        'id' => 45,
        'title' => 'Mental Health Awareness',
        'category' => 'healthcare',
        'duration' => '5 weeks',
        'level' => 'Beginner',
        'rating' => 4.9,
        'enrolled' => 2000,
        'description' => 'Understand mental health issues and how to support individuals in need.',
        'skills' => array('Mental Health', 'Counseling', 'Crisis Intervention')
    ),
    array(
        'id' => 46,
        'title' => 'Advanced Clinical Research',
        'category' => 'healthcare',
        'duration' => '10 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 1500,
        'description' => 'Conduct and manage clinical research studies effectively.',
        'skills' => array('Clinical Trials', 'Research Methodology', 'Ethical Practices')
    ),
    array(
        'id' => 47,
        'title' => 'Healthcare Leadership',
        'category' => 'healthcare',
        'duration' => '7 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1700,
        'description' => 'Develop leadership skills for managing healthcare teams and organizations.',
        'skills' => array('Leadership', 'Healthcare Management', 'Team Building')
    ),
    array(
        'id' => 48,
        'title' => 'Public Relations Strategies',
        'category' => 'media & communications',
        'duration' => '6 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 1600,
        'description' => 'Learn effective public relations strategies to manage brand reputation.',
        'skills' => array('Public Relations', 'Crisis Management', 'Media Relations')
    ),
    array(
        'id' => 49,
        'title' => 'Content Marketing Essentials',
        'category' => 'media & communications',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.5,
        'enrolled' => 1900,
        'description' => 'Master the basics of content marketing to engage and grow your audience.',
        'skills' => array('Content Creation', 'SEO', 'Audience Engagement')
    ),
    array(
        'id' => 50,
        'title' => 'Visual Storytelling',
        'category' => 'media & communications',
        'duration' => '7 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1400,
        'description' => 'Use visual media to tell compelling stories and connect with audiences.',
        'skills' => array('Storytelling', 'Visual Design', 'Multimedia Production')
    ),
    array(
        'id' => 51,
        'title' => 'Podcast Production',
        'category' => 'media & communications',
        'duration' => '5 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 1300,
        'description' => 'Learn the essentials of creating and producing engaging podcasts.',
        'skills' => array('Audio Production', 'Content Planning', 'Interview Techniques')
    ),
    array(
        'id' => 52,
        'title' => 'Media Ethics and Law',
        'category' => 'media & communications',
        'duration' => '9 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 1200,
        'description' => 'Understand the ethical and legal considerations in media and communications.',
        'skills' => array('Media Law', 'Ethical Decision Making', 'Regulatory Compliance')
    ),
    array(
        'id' => 53,
        'title' => 'Family Law Fundamentals',
        'category' => 'law',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.5,
        'enrolled' => 1400,
        'description' => 'Explore the basics of family law, including marriage, divorce, and child custody.',
        'skills' => array('Family Law', 'Legal Procedures', 'Case Management')
    ),
    array(
        'id' => 54,
        'title' => 'International Law and Human Rights',
        'category' => 'law',
        'duration' => '10 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 1100,
        'description' => 'Understand international law and the protection of human rights.',
        'skills' => array('International Law', 'Human Rights', 'Legal Advocacy')
    ),
    array(
        'id' => 55,
        'title' => 'Environmental Law and Policy',
        'category' => 'law',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1300,
        'description' => 'Learn about the legal frameworks governing environmental protection.',
        'skills' => array('Environmental Law', 'Policy Analysis', 'Regulatory Compliance')
    ),
    array(
        'id' => 56,
        'title' => 'Intellectual Property Law',
        'category' => 'law',
        'duration' => '7 weeks',
        'level' => 'Intermediate',
        'rating' => 4.8,
        'enrolled' => 1200,
        'description' => 'Explore the principles of intellectual property law and its applications.',
        'skills' => array('IP Law', 'Patent Law', 'Trademark Law')
    ),
    array(
        'id' => 57,
        'title' => 'Cyber Law and Digital Rights',
        'category' => 'law',
        'duration' => '9 weeks',
        'level' => 'Advanced',
        'rating' => 4.7,
        'enrolled' => 1000,
        'description' => 'Understand the legal issues related to cyberspace and digital rights.',
        'skills' => array('Cyber Law', 'Digital Rights', 'Data Privacy')
    ),
    array(
        'id' => 58,
        'title' => 'Cultural Anthropology',
        'category' => 'social science',
        'duration' => '7 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 1800,
        'description' => 'Study human cultures and societies from an anthropological perspective.',
        'skills' => array('Anthropology', 'Cultural Studies', 'Ethnographic Research')
    ),
    array(
        'id' => 59,
        'title' => 'Political Science and Governance',
        'category' => 'social science',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1600,
        'description' => 'Explore the principles of political science and the functioning of governments.',
        'skills' => array('Political Theory', 'Governance', 'Policy Analysis')
    ),
    array(
        'id' => 60,
        'title' => 'Social Psychology',
        'category' => 'social science',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.5,
        'enrolled' => 2000,
        'description' => 'Understand how social influences affect individual behavior and interactions.',
        'skills' => array('Social Psychology', 'Behavioral Analysis', 'Research Methods')
    ),
    array(
        'id' => 61,
        'title' => 'Economic Sociology',
        'category' => 'social science',
        'duration' => '9 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 1400,
        'description' => 'Study the social aspects of economic behavior and institutions.',
        'skills' => array('Economic Sociology', 'Institutional Analysis', 'Social Theory')
    ),
    array(
        'id' => 62,
        'title' => 'Gender Studies',
        'category' => 'social science',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1500,
        'description' => 'Explore the social and cultural constructions of gender and their impacts.',
        'skills' => array('Gender Theory', 'Cultural Analysis', 'Social Research')
    ),
    array(
        'id' => 63,
        'title' => 'Urban Sociology',
        'category' => 'social science',
        'duration' => '7 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 1400,
        'description' => 'Study the social structures and processes in urban environments.',
        'skills' => array('Urban Studies', 'Sociological Theory', 'Field Research')
    ),
    array(
        'id' => 64,
        'title' => 'Social Movements and Change',
        'category' => 'social science',
        'duration' => '9 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 1300,
        'description' => 'Analyze the development and impact of social movements.',
        'skills' => array('Social Change', 'Activism', 'Policy Analysis')
    ),
    array(
        'id' => 65,
        'title' => 'Criminology',
        'category' => 'social science',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1600,
        'description' => 'Understand the causes and consequences of criminal behavior.',
        'skills' => array('Criminology', 'Legal Studies', 'Behavioral Analysis')
    ),
    array(
        'id' => 66,
        'title' => 'Globalization and Society',
        'category' => 'social science',
        'duration' => '10 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 1200,
        'description' => 'Examine the effects of globalization on social structures and cultures.',
        'skills' => array('Global Studies', 'Cultural Analysis', 'Sociological Theory')
    ),
    array(
        'id' => 67,
        'title' => 'Auditing Principles and Practices',
        'category' => 'accountancy',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 2100,
        'description' => 'Learn the fundamentals of auditing and assurance services.',
        'skills' => array('Auditing', 'Risk Assessment', 'Internal Controls')
    ),
    array(
        'id' => 68,
        'title' => 'Taxation and Tax Planning',
        'category' => 'accountancy',
        'duration' => '10 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 1800,
        'description' => 'Understand the principles of taxation and strategies for tax planning.',
        'skills' => array('Tax Planning', 'Tax Compliance', 'Financial Reporting')
    ),
    array(
        'id' => 69,
        'title' => 'Forensic Accounting',
        'category' => 'accountancy',
        'duration' => '9 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 1600,
        'description' => 'Explore the techniques used in forensic accounting and fraud detection.',
        'skills' => array('Forensic Accounting', 'Fraud Detection', 'Investigative Techniques')
    ),
    array(
        'id' => 70,
        'title' => 'Accounting Information Systems',
        'category' => 'accountancy',
        'duration' => '7 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 1900,
        'description' => 'Learn about the systems and technologies used in accounting.',
        'skills' => array('Information Systems', 'Data Management', 'System Analysis')
    ),
    array(
        'id' => 71,
        'title' => 'Cost Accounting',
        'category' => 'accountancy',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 2000,
        'description' => 'Understand the principles and methods of cost accounting.',
        'skills' => array('Cost Analysis', 'Budgeting', 'Financial Management')
    ),
    array(
        'id' => 72,
        'title' => 'International Accounting Standards',
        'category' => 'accountancy',
        'duration' => '10 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 1700,
        'description' => 'Learn about the international standards governing accounting practices.',
        'skills' => array('IFRS', 'Global Accounting', 'Regulatory Compliance')
    ),
    array(
        'id' => 73,
        'title' => 'Financial Statement Analysis',
        'category' => 'accountancy',
        'duration' => '9 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 1500,
        'description' => 'Analyze financial statements to assess the financial health of organizations.',
        'skills' => array('Financial Analysis', 'Ratio Analysis', 'Investment Analysis')
    )
);
header('Content-Type: application/json');


echo json_encode($courses);
?>