<?php
$courses = array(
    array(
        'id' => 1,
        'title' => 'Introduction to Web Development',
        'category' => 'Information Technology',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.5,
        'enrolled' => 1234,
        'description' => 'Learn the fundamentals of web development including HTML, CSS, and JavaScript.',
        'skills' => array('HTML', 'CSS', 'JavaScript')
    ),
    array(
        'id' => 2,
        'title' => 'Business Communication',
        'category' => 'Marketing & Advertising',
        'duration' => '4 weeks',
        'level' => 'Intermediate',
        'rating' => 4.8,
        'enrolled' => 2156,
        'description' => 'Master the art of professional communication in the workplace.',
        'skills' => array('Communication', 'Presentation', 'Writing')
    ),
    array(
        'id' => 3,
        'title' => 'UI/UX Design Fundamentals',
        'category' => 'Design',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 1789,
        'description' => 'Learn the principles of user interface and experience design.',
        'skills' => array('Figma', 'Design Thinking', 'Prototyping')
    ),
    array(
        'id' => 4,
        'title' => 'Python for Data Science',
        'category' => 'Information Technology',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 3421,
        'description' => 'Master Python programming for data analysis and visualization.',
        'skills' => array('Python', 'Pandas', 'NumPy', 'Matplotlib')
    ),
    array(
        'id' => 5,
        'title' => 'Digital Marketing Essentials',
        'category' => 'Marketing & Advertising',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.4,
        'enrolled' => 2890,
        'description' => 'Learn core concepts of digital marketing and social media strategy.',
        'skills' => array('Social Media', 'SEO', 'Content Marketing')
    ),
    array(
        'id' => 6,
        'title' => 'Project Management Fundamentals',
        'category' => 'Soft Skills',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.9,
        'enrolled' => 1567,
        'description' => 'Learn essential project management methodologies and tools.',
        'skills' => array('Agile', 'Scrum', 'Project Planning')
    ),
    array(
        'id' => 7,
        'title' => 'React.js Development',
        'category' => 'Information Technology',
        'duration' => '12 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 2345,
        'description' => 'Build modern web applications using React.js and its ecosystem.',
        'skills' => array('React', 'Redux', 'JavaScript', 'REST APIs')
    ),
    array(
        'id' => 8,
        'title' => 'Leadership & Team Management',
        'category' => 'Soft Skills',
        'duration' => '5 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1890,
        'description' => 'Develop essential leadership skills for managing teams effectively.',
        'skills' => array('Leadership', 'Conflict Resolution', 'Team Building')
    ),
    array(
        'id' => 9,
        'title' => 'Data Analytics with SQL',
        'category' => 'Information Technology',
        'duration' => '7 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 2678,
        'description' => 'Master SQL for data analysis and database management.',
        'skills' => array('SQL', 'Database Design', 'Data Analysis')
    ),
    array(
        'id' => 10,
        'title' => 'Brand Strategy & Marketing',
        'category' => 'Marketing & Advertising',
        'duration' => '6 weeks',
        'level' => 'Intermediate',
        'rating' => 4.5,
        'enrolled' => 1456,
        'description' => 'Learn to build and maintain strong brand presence in the market.',
        'skills' => array('Brand Management', 'Marketing Strategy', 'Consumer Behavior')
    ),
    array(
        'id' => 11,
        'title' => 'Mobile App Design',
        'category' => 'Design',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1234,
        'description' => 'Create engaging mobile app interfaces and experiences.',
        'skills' => array('Mobile UI', 'Interaction Design', 'Wireframing')
    ),
    array(
        'id' => 12,
        'title' => 'Public Speaking Mastery',
        'category' => 'Soft Skills',
        'duration' => '4 weeks',
        'level' => 'Beginner',
        'rating' => 4.8,
        'enrolled' => 3456,
        'description' => 'Build confidence and master the art of public speaking.',
        'skills' => array('Public Speaking', 'Storytelling', 'Audience Engagement')
    ),
    array(
        'id' => 13,
        'title' => 'Machine Learning Basics',
        'category' => 'Information Technology',
        'duration' => '12 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 1789,
        'description' => 'Introduction to machine learning algorithms and applications.',
        'skills' => array('Python', 'Scikit-learn', 'TensorFlow')
    ),
    array(
        'id' => 14,
        'title' => 'Financial Management',
        'category' => 'Finance and Banking',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 2134,
        'description' => 'Understand key concepts of financial management and analysis.',
        'skills' => array('Financial Analysis', 'Budgeting', 'Risk Management')
    ),
    array(
        'id' => 15,
        'title' => 'Cloud Computing Fundamentals',
        'category' => 'Information Technology',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1567,
        'description' => 'Learn basic concepts of cloud computing and major platforms.',
        'skills' => array('AWS', 'Azure', 'Cloud Architecture')
    ),
    array(
        'id' => 16,
        'title' => 'Cybersecurity Essentials',
        'category' => 'Information Technology',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.8,
        'enrolled' => 2345,
        'description' => 'Learn fundamental concepts of cybersecurity and network protection.',
        'skills' => array('Network Security', 'Cryptography', 'Security Protocols')
    ),
    array(
        'id' => 17,
        'title' => 'Content Creation & Strategy',
        'category' => 'Marketing & Advertising',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 1890,
        'description' => 'Master the art of creating engaging content across different platforms.',
        'skills' => array('Content Writing', 'Video Production', 'Social Media Strategy')
    ),
    array(
        'id' => 18,
        'title' => 'Advanced Data Visualization',
        'category' => 'Information Technology',
        'duration' => '8 weeks',
        'level' => 'Advanced',
        'rating' => 4.7,
        'enrolled' => 1456,
        'description' => 'Create compelling data stories using advanced visualization techniques.',
        'skills' => array('Tableau', 'D3.js', 'Data Storytelling')
    ),
    array(
        'id' => 19,
        'title' => 'Agile Product Management',
        'category' => 'Soft Skills',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.9,
        'enrolled' => 2156,
        'description' => 'Learn to manage product development using agile methodologies.',
        'skills' => array('Product Strategy', 'Scrum', 'User Stories')
    ),
    array(
        'id' => 20,
        'title' => 'Motion Graphics Design',
        'category' => 'Design',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.8,
        'enrolled' => 1678,
        'description' => 'Create engaging motion graphics for digital platforms.',
        'skills' => array('After Effects', 'Animation', 'Visual Storytelling')
    ),
    array(
        'id' => 21,
        'title' => 'Emotional Intelligence at Work',
        'category' => 'Soft Skills',
        'duration' => '4 weeks',
        'level' => 'Beginner',
        'rating' => 4.7,
        'enrolled' => 2890,
        'description' => 'Develop emotional intelligence skills for better workplace relationships.',
        'skills' => array('Self-awareness', 'Empathy', 'Relationship Management')
    ),
    array(
        'id' => 22,
        'title' => 'DevOps Engineering',
        'category' => 'Information Technology',
        'duration' => '12 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 1567,
        'description' => 'Master modern DevOps practices and tools.',
        'skills' => array('Docker', 'Jenkins', 'Kubernetes')
    ),
    array(
        'id' => 23,
        'title' => 'Advanced Excel for Business',
        'category' => 'Finance and Banking',
        'duration' => '6 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 3421,
        'description' => 'Master advanced Excel functions for business analysis.',
        'skills' => array('Excel', 'Pivot Tables', 'Macros')
    ),
    array(
        'id' => 24,
        'title' => 'Natural Language Processing',
        'category' => 'Information Technology',
        'duration' => '10 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 1234,
        'description' => 'Learn to process and analyze text data using AI techniques.',
        'skills' => array('Python', 'NLTK', 'SpaCy')
    ),
    array(
        'id' => 25,
        'title' => '3D Design Fundamentals',
        'category' => 'Design',
        'duration' => '12 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1890,
        'description' => 'Learn the basics of 3D modeling and rendering.',
        'skills' => array('Blender', '3D Modeling', 'Texturing')
    ),
    array(
        'id' => 26,
        'title' => 'Email Marketing Mastery',
        'category' => 'Marketing & Advertising',
        'duration' => '5 weeks',
        'level' => 'Intermediate',
        'rating' => 4.5,
        'enrolled' => 2156,
        'description' => 'Create effective email marketing campaigns and strategies.',
        'skills' => array('Email Design', 'Campaign Management', 'Analytics')
    ),
    array(
        'id' => 27,
        'title' => 'Critical Thinking and Problem Solving',
        'category' => 'Soft Skills',
        'duration' => '6 weeks',
        'level' => 'Intermediate',
        'rating' => 4.8,
        'enrolled' => 1789,
        'description' => 'Develop advanced problem-solving and analytical thinking skills.',
        'skills' => array('Analysis', 'Decision Making', 'Logic')
    ),
    array(
        'id' => 28,
        'title' => 'Blockchain Development',
        'category' => 'Information Technology',
        'duration' => '12 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 1456,
        'description' => 'Learn to build applications using blockchain technology.',
        'skills' => array('Solidity', 'Smart Contracts', 'Web3.js')
    ),
    array(
        'id' => 29,
        'title' => 'Business Analytics',
        'category' => 'Finance and Banking',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 2678,
        'description' => 'Learn to use data analytics for business decision making.',
        'skills' => array('Data Analysis', 'Business Intelligence', 'Reporting')
    ),
    array(
        'id' => 30,
        'title' => 'Game Design Principles',
        'category' => 'Design',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 1567,
        'description' => 'Master the fundamentals of game design and development.',
        'skills' => array('Game Mechanics', 'Level Design', 'Unity')
    ),
    array(
        'id' => 31,
        'title' => 'Introduction to Healthcare Management',
        'category' => 'Healthcare',
        'duration' => '6 weeks',
        'level' => 'Beginner',
        'rating' => 4.8,
        'enrolled' => 1890,
        'description' => 'Learn the basics of managing healthcare facilities and services.',
        'skills' => array('Healthcare Administration', 'Patient Care', 'Health Policy')
    ),
    array(
        'id' => 32,
        'title' => 'Public Health and Epidemiology',
        'category' => 'Healthcare',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.9,
        'enrolled' => 2100,
        'description' => 'Understand the principles of public health and the study of disease patterns.',
        'skills' => array('Epidemiology', 'Public Health Policy', 'Disease Prevention')
    ),
    array(
        'id' => 33,
        'title' => 'Digital Media Strategies',
        'category' => 'Media & Communications',
        'duration' => '7 weeks',
        'level' => 'Intermediate',
        'rating' => 4.5,
        'enrolled' => 1750,
        'description' => 'Explore strategies for effective digital media campaigns.',
        'skills' => array('Digital Marketing',)
    ),
    array(
        'id' => 34,
        'title' => 'Introduction to Criminal Law',
        'category' => 'Law',
        'duration' => '10 weeks',
        'level' => 'Beginner',
        'rating' => 4.7,
        'enrolled' => 890,
        'description' => 'Understand the basics of criminal law, including key concepts and case studies.',
        'skills' => array('Legal Research', 'Case Analysis', 'Criminal Law')
    ),
    array(
        'id' => 35,
        'title' => 'Corporate Law Essentials',
        'category' => 'Law',
        'duration' => '12 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 760,
        'description' => 'Learn about corporate law, including company formation, governance, and compliance.',
        'skills' => array('Corporate Governance', 'Legal Compliance', 'Business Law')
    ),
    array(
        'id' => 36,
        'title' => 'Family Law Fundamentals',
        'category' => 'Law',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.5,
        'enrolled' => 540,
        'description' => 'Explore the principles of family law, including marriage, divorce, and child custody.',
        'skills' => array('Family Law', 'Legal Documentation', 'Client Counseling')
    ),
    array(
        'id' => 37,
        'title' => 'International Law and Human Rights',
        'category' => 'Law',
        'duration' => '14 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 430,
        'description' => 'Study international law and human rights, focusing on global legal frameworks and issues.',
        'skills' => array('International Law', 'Human Rights Advocacy', 'Legal Analysis')
    ),
    array(
        'id' => 38,
        'title' => 'Environmental Law and Policy',
        'category' => 'Law',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 620,
        'description' => 'Learn about environmental law and policy, including regulations and sustainability practices.',
        'skills' => array('Environmental Law', 'Policy Analysis', 'Sustainability')
    ),
    array(
        'id' => 39,
        'title' => 'Introduction to Journalism',
        'category' => 'Media & Communications',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 980,
        'description' => 'Learn the basics of journalism, including news writing, reporting, and ethics.',
        'skills' => array('News Writing', 'Reporting', 'Media Ethics')
    ),
    array(
        'id' => 40,
        'title' => 'Digital Marketing Strategies',
        'category' => 'Media & Communications',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1120,
        'description' => 'Explore digital marketing strategies, including SEO, social media, and content marketing.',
        'skills' => array('SEO', 'Social Media Marketing', 'Content Creation')
    ),
    array(
        'id' => 41,
        'title' => 'Public Relations and Media Management',
        'category' => 'Media & Communications',
        'duration' => '12 weeks',
        'level' => 'Intermediate',
        'rating' => 4.5,
        'enrolled' => 870,
        'description' => 'Understand public relations and media management, including crisis communication and branding.',
        'skills' => array('Public Relations', 'Media Management', 'Crisis Communication')
    ),
    array(
        'id' => 42,
        'title' => 'Film Production Basics',
        'category' => 'Media & Communications',
        'duration' => '14 weeks',
        'level' => 'Beginner',
        'rating' => 4.8,
        'enrolled' => 650,
        'description' => 'Learn the fundamentals of film production, including directing, editing, and cinematography.',
        'skills' => array('Directing', 'Editing', 'Cinematography')
    ),
    array(
        'id' => 43,
        'title' => 'Advanced Communication Skills',
        'category' => 'Media & Communications',
        'duration' => '8 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 720,
        'description' => 'Enhance your communication skills, including public speaking, negotiation, and persuasion.',
        'skills' => array('Public Speaking', 'Negotiation', 'Persuasion')
    ),
    array(
        'id' => 44,
        'title' => 'Introduction to Sociology',
        'category' => 'Social Science',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.5,
        'enrolled' => 1100,
        'description' => 'Learn the basics of sociology, including social structures, institutions, and relationships.',
        'skills' => array('Sociological Analysis', 'Research Methods', 'Critical Thinking')
    ),
    array(
        'id' => 45,
        'title' => 'Psychology 101',
        'category' => 'Social Science',
        'duration' => '10 weeks',
        'level' => 'Beginner',
        'rating' => 4.7,
        'enrolled' => 950,
        'description' => 'Explore the fundamentals of psychology, including human behavior, cognition, and emotions.',
        'skills' => array('Behavioral Analysis', 'Cognitive Psychology', 'Emotional Intelligence')
    ),
    array(
        'id' => 46,
        'title' => 'Cultural Anthropology',
        'category' => 'Social Science',
        'duration' => '12 weeks',
        'level' => 'Intermediate',
        'rating' => 4.6,
        'enrolled' => 780,
        'description' => 'Study cultural anthropology, focusing on human cultures, traditions, and social practices.',
        'skills' => array('Cultural Analysis', 'Ethnography', 'Social Research')
    ),
    array(
        'id' => 47,
        'title' => 'Political Science Basics',
        'category' => 'Social Science',
        'duration' => '10 weeks',
        'level' => 'Beginner',
        'rating' => 4.5,
        'enrolled' => 860,
        'description' => 'Understand the basics of political science, including political systems, theories, and policies.',
        'skills' => array('Political Analysis', 'Policy Evaluation', 'Critical Thinking')
    ),
    array(
        'id' => 48,
        'title' => 'Social Psychology',
        'category' => 'Social Science',
        'duration' => '8 weeks',
        'level' => 'Intermediate',
        'rating' => 4.8,
        'enrolled' => 720,
        'description' => 'Explore social psychology, focusing on how individuals influence and are influenced by others.',
        'skills' => array('Social Behavior Analysis', 'Group Dynamics', 'Interpersonal Skills')
    ),
    array(
        'id' => 49,
        'title' => 'Teaching Strategies for the Classroom',
        'category' => 'Education and Training',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 980,
        'description' => 'Learn effective teaching strategies to engage students and enhance learning outcomes.',
        'skills' => array('Lesson Planning', 'Classroom Management', 'Student Engagement')
    ),
    array(
        'id' => 50,
        'title' => 'Educational Psychology',
        'category' => 'Education and Training',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 870,
        'description' => 'Understand the principles of educational psychology and how they apply to teaching and learning.',
        'skills' => array('Educational Theory', 'Learning Strategies', 'Student Assessment')
    ),
    array(
        'id' => 51,
        'title' => 'Curriculum Development',
        'category' => 'Education and Training',
        'duration' => '12 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 650,
        'description' => 'Learn how to develop effective curricula that meet educational standards and student needs.',
        'skills' => array('Curriculum Design', 'Educational Standards', 'Instructional Design')
    ),
    array(
        'id' => 51,
        'title' => 'Introduction to Mechanical Engineering',
        'category' => 'Engineering',
        'duration' => '10 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 890,
        'description' => 'Learn the basics of mechanical engineering, including thermodynamics, mechanics, and materials science.',
        'skills' => array('Thermodynamics', 'Mechanics', 'Materials Science')
    ),
    array(
        'id' => 52,
        'title' => 'Electrical Engineering Fundamentals',
        'category' => 'Engineering',
        'duration' => '12 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 760,
        'description' => 'Understand the principles of electrical engineering, including circuits, signals, and systems.',
        'skills' => array('Circuit Analysis', 'Signal Processing', 'Systems Engineering')
    ),
    array(
        'id' => 53,
        'title' => 'Civil Engineering Basics',
        'category' => 'Engineering',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.5,
        'enrolled' => 540,
        'description' => 'Explore the fundamentals of civil engineering, including structural analysis, construction, and geotechnics.',
        'skills' => array('Structural Analysis', 'Construction Management', 'Geotechnical Engineering')
    ),
    array(
        'id' => 54,
        'title' => 'Introduction to Chemical Engineering',
        'category' => 'Engineering',
        'duration' => '14 weeks',
        'level' => 'Advanced',
        'rating' => 4.8,
        'enrolled' => 430,
        'description' => 'Study the basics of chemical engineering, including process design, thermodynamics, and reaction engineering.',
        'skills' => array('Process Design', 'Thermodynamics', 'Reaction Engineering')
    ),
    array(
        'id' => 55,
        'title' => 'Software Engineering Principles',
        'category' => 'Engineering',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 620,
        'description' => 'Learn about software engineering principles, including software development methodologies, testing, and maintenance.',
        'skills' => array('Software Development', 'Testing', 'Maintenance')
    ),
    array(
        'id' => 56,
        'title' => 'Retail Management Basics',
        'category' => 'Retail and Customer Service',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 980,
        'description' => 'Learn the fundamentals of retail management, including store operations, merchandising, and customer service.',
        'skills' => array('Store Operations', 'Merchandising', 'Customer Service')
    ),
    array(
        'id' => 57,
        'title' => 'Customer Service Excellence',
        'category' => 'Retail and Customer Service',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1120,
        'description' => 'Understand the principles of excellent customer service, including communication skills, problem-solving, and customer satisfaction.',
        'skills' => array('Communication Skills', 'Problem-Solving', 'Customer Satisfaction')
    ),
    array(
        'id' => 58,
        'title' => 'Sales Techniques and Strategies',
        'category' => 'Retail and Customer Service',
        'duration' => '12 weeks',
        'level' => 'Intermediate',
        'rating' => 4.5,
        'enrolled' => 870,
        'description' => 'Explore effective sales techniques and strategies, including prospecting, closing deals, and relationship management.',
        'skills' => array('Prospecting', 'Closing Deals', 'Relationship Management')
    ),
    array(
        'id' => 59,
        'title' => 'E-commerce Essentials',
        'category' => 'Retail and Customer Service',
        'duration' => '14 weeks',
        'level' => 'Beginner',
        'rating' => 4.8,
        'enrolled' => 650,
        'description' => 'Learn the basics of e-commerce, including online store setup, digital marketing, and customer engagement.',
        'skills' => array('Online Store Setup', 'Digital Marketing', 'Customer Engagement')
    ),
    array(
        'id' => 60,
        'title' => 'Retail Analytics and Insights',
        'category' => 'Retail and Customer Service',
        'duration' => '10 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 720,
        'description' => 'Understand retail analytics and insights, including data analysis, inventory management, and sales forecasting.',
        'skills' => array('Data Analysis', 'Inventory Management', 'Sales Forecasting')
    ),
    array(
        'id' => 61,
        'title' => 'Introduction to Hospitality Management',
        'category' => 'Hospitality and Tourism',
        'duration' => '8 weeks',
        'level' => 'Beginner',
        'rating' => 4.6,
        'enrolled' => 980,
        'description' => 'Learn the basics of hospitality management, including hotel operations, guest services, and event planning.',
        'skills' => array('Hotel Operations', 'Guest Services', 'Event Planning')
    ),
    array(
        'id' => 62,
        'title' => 'Tourism Management Fundamentals',
        'category' => 'Hospitality and Tourism',
        'duration' => '10 weeks',
        'level' => 'Intermediate',
        'rating' => 4.7,
        'enrolled' => 1120,
        'description' => 'Understand the principles of tourism management, including destination marketing, tour operations, and travel planning.',
        'skills' => array('Destination Marketing', 'Tour Operations', 'Travel Planning')
    ),
    array(
        'id' => 63,
        'title' => 'Culinary Arts Basics',
        'category' => 'Hospitality and Tourism',
        'duration' => '12 weeks',
        'level' => 'Intermediate',
        'rating' => 4.5,
        'enrolled' => 870,
        'description' => 'Explore the fundamentals of culinary arts, including cooking techniques, food safety, and menu planning.',
        'skills' => array('Cooking Techniques', 'Food Safety', 'Menu Planning')
    ),
    array(
        'id' => 64,
        'title' => 'Event Management Essentials',
        'category' => 'Hospitality and Tourism',
        'duration' => '14 weeks',
        'level' => 'Beginner',
        'rating' => 4.8,
        'enrolled' => 650,
        'description' => 'Learn the basics of event management, including event planning, coordination, and execution.',
        'skills' => array('Event Planning', 'Coordination', 'Execution')
    ),
    array(
        'id' => 65,
        'title' => 'Sustainable Tourism Practices',
        'category' => 'Hospitality and Tourism',
        'duration' => '10 weeks',
        'level' => 'Advanced',
        'rating' => 4.9,
        'enrolled' => 720,
        'description' => 'Understand sustainable tourism practices, including eco-friendly travel, community engagement, and conservation efforts.',
        'skills' => array('Eco-Friendly Travel', 'Community Engagement', 'Conservation')
    )
    
);
header('Content-Type: application/json');


echo json_encode($courses);
?>